### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by ghost** [Spirals-Team/hadoop-benchmark#3]
How can I install docker and docker-machine inside user folder on Grid5000?

**Comment by zhangbbo** [comment]
To install Docker and Docker-machine in fontend, we can not install them directly by the installation package in Docker website.
So we must install them by binary files.
you can use the command provided in Tutoriel: 

$ curl -L https://github.com/docker/machine/releases/download/v0.5.6/docker-machine_linux-amd64 > /home/bzhang/docker-machine && chmod +x /home/bzhang/docker-machine

$ curl -L https://get.docker.com/builds/Linux/x86_64/docker-latest > /home/bzhang/docker && chmod +x /home/bzhang/docker

The two above commands are my example to install docker and docker-machine to my home folder.
You just replace "bzhang" with your username and should be able to well install docker in your folder.

**Comment by ghost** [comment]
Trying, but says: 

> curl: (7) couldn't connect to host

**Comment by zhangbbo** [comment]
I just try.
They work well.
I achieve it in Nancy site.
You can also have a try in Nancy site.

**Comment by ghost** [comment]
Could you please make a try on Lyon?

**Comment by ghost** [comment]
That seems okay now! Thanks a lot!

**Comment by zhangbbo** [comment]
They also work on Lyon site.....
Can you show me the commands you used?

**Comment by zhangbbo** [comment]
You are welcome. :)

**Comment by rouvoy** [comment]
Fixed by commit b9891e6
