### ISSUE TITLE
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded

### ISSUE THREAD

**Issue by ghost** [Spirals-Team/hadoop-benchmark#5]
There is a problem with Docker. It started successfully 2 virtual machines, and throw an error when creating third one.

`Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded`

I have eliminated all the other problems, but it appears maybe randomly.

**Comment by zhangbbo** [comment]
Yes, I also meet this problem in Lyon site.
In Lyon site, it happens with high probability.
But in Nancy site, it probably doesn't happen.
It looks like highly depend on the machines or environment used.
