### ISSUE TITLE
MapReduce function memory values

### ISSUE THREAD

**Issue by ghost** [Spirals-Team/hadoop-benchmark#6]
Where can these values set in this system: `yarn.scheduler.maximum-allocation-mb, mapreduce.map.memory.mb, mapreduce.map.java.opts, mapreduce.reduce.memory.mb, mapreduce.reduce.java.opts?
`
I haven't found containing XML files.

**Comment by zhangbbo** [comment]
In directory "images/hadoop/hadoop-conf/", there are all the configuration files used to configure the Hadoop system.

**Comment by ghost** [comment]
Yes, but I couldn't see these YARN related values in those files.

**Comment by zhangbbo** [comment]
That means we used the default values. :)
You just need to add the related YARN parameter in the correct file with your preferred value.
When you launch the Hadoop container, the system will apply your configuration automatically.
